# Generated by Django 6.0.4 on 2026-05-18 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankey', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('open', 'Menunggu'), ('in_progress', 'Diproses'), ('closed', 'Selesai')], default='open', max_length=15),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('transfer', 'Transfer & Pembayaran'), ('account', 'Akun & Keamanan'), ('card', 'Kartu & ATM'), ('loan', 'Pinjaman & Kredit'), ('other', 'Lainnya')], default='other', max_length=50),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=16, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=1000000.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('credit', 'Masuk'), ('debit', 'Keluar'), ('transfer_in', 'Transfer Masuk'), ('transfer_out', 'Transfer Keluar')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('related_account', models.CharField(blank=True, max_length=16, null=True)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bankey.bankaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
